List<String> contentList = [
  'Home',
  'About',
  'Education',
  'Experience',
  'Portfolio',
  'Contact'
];

var skill = {
  'Flutter': 'Advance',
  'Dart': 'Advance',
  'Java': 'Advance',
  'Nodejs': 'Intermediate',
  'ExpressJS': 'Intermediate',
  'MongoDB': 'Intermediate',
  'AngularJS': 'Intermediate',
  'Python': 'Advance',
  'JavaScript': 'Intermediate',
  'Object Oriented Programming': 'Advance',
  'Data Structures': 'Intermediate',
  'MEAN stack': 'Intermediate',
  'Html': 'Intermediate',
  'C++': 'Intermediate',
  'CSS': 'Beginner',
  'Data Science': 'Beginner',
  'Data analytics': 'Beginner',
  'Firebase': 'Intermediate',
  'Rest Api': 'Advance',
  'Git': 'Advance',
  'Github': 'Advance',
  'Gitlab': 'Advance',
  'Android Studio': 'Intermediate',
  'Postman': 'Advance',
};
